// FRONTEND CON REACT/src/components/ui/Calendar.tsx
import React, { useState } from 'react';
import { ChevronLeft, ChevronRight, Calendar as CalendarIcon } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Typography } from '@/components/ui/Typography';

interface CalendarProps {
  selectedDate?: string; // YYYY-MM-DD
  onDateSelect: (date: string) => void;
  minDate?: string;
  maxDate?: string;
}

export const Calendar: React.FC<CalendarProps> = ({
  selectedDate,
  onDateSelect,
  minDate,
  maxDate,
}) => {
  const [currentMonth, setCurrentMonth] = useState(new Date());

  const daysInMonth = (date: Date) => {
    return new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate();
  };

  const startDayOfMonth = (date: Date) => {
    const day = new Date(date.getFullYear(), date.getMonth(), 1).getDay();
    // Ajustar para que la semana empiece en Lunes (0=Dom, 1=Lun...)
    return day === 0 ? 6 : day - 1;
  };

  const isToday = (day: number) => {
    const today = new Date();
    return (
      day === today.getDate() &&
      currentMonth.getMonth() === today.getMonth() &&
      currentMonth.getFullYear() === today.getFullYear()
    );
  };

  const isSelected = (day: number) => {
    if (!selectedDate) return false;
    const date = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), day + 1);
    const dateStr = date.toISOString().split('T')[0];
    return dateStr === selectedDate;
  };

  const isDisabled = (day: number) => {
    const date = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), day);
    const dateStr = date.toISOString().split('T')[0];
    
    if (minDate && dateStr < minDate) return true;
    if (maxDate && dateStr > maxDate) return true;
    return false;
  };

  const months = [
    'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
    'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
  ];

  const daysOfWeek = ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'];

  const prevMonth = () => {
    setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() - 1));
  };

  const nextMonth = () => {
    setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1));
  };

  const handleDateClick = (day: number) => {
    if (isDisabled(day)) return;
    const date = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), day + 1);
    onDateSelect(date.toISOString().split('T')[0]);
  };

  const calendarDays = [];
  const totalDays = daysInMonth(currentMonth);
  const startOffset = startDayOfMonth(currentMonth);

  for (let i = 0; i < startOffset; i++) {
    calendarDays.push(<div key={`empty-${i}`} className="h-10 w-px0" />);
  }

  for (let d = 1; d <= totalDays; d++) {
    const disabled = isDisabled(d);
    calendarDays.push(
      <button
        key={d}
        onClick={() => handleDateClick(d)}
        disabled={disabled}
        className={cn(
          "h-10 w-px0 rounded-full flex items-center justify-center text-sm transition-all focus:outline-none",
          isSelected(d) ? "bg-primary text-white font-bold shadow-lg scale-110" : "hover:bg-primary/10 text-gray-700",
          isToday(d) && !isSelected(d) && "border-2 border-primary text-primary font-bold",
          disabled && "text-gray-300 pointer-events-none"
        )}
      >
        {d}
      </button>
    );
  }

  return (
    <div className="p-6 bg-white rounded-4xl shadow-xl shadow-gray-200/50 border border-gray-100 max-w-sm mx-auto">
      <div className="flex items-center justify-between mb-6">
        <Typography variant="h4" className="m-0 font-bold text-gray-800">
          {months[currentMonth.getMonth()]} {currentMonth.getFullYear()}
        </Typography>
        <div className="flex gap-2">
          <button 
            onClick={prevMonth}
            className="p-2 hover:bg-gray-100 rounded-full text-gray-500 transition-colors"
          >
            <ChevronLeft size={20} />
          </button>
          <button 
            onClick={nextMonth}
            className="p-2 hover:bg-gray-100 rounded-full text-gray-500 transition-colors"
          >
            <ChevronRight size={20} />
          </button>
        </div>
      </div>

      <div className="grid grid-cols-7 gap-1 mb-2">
        {daysOfWeek.map(day => (
          <div key={day} className="h-10 flex items-center justify-center text-xs font-bold text-gray-400 uppercase tracking-wider">
            {day}
          </div>
        ))}
      </div>

      <div className="grid grid-cols-7 gap-1">
        {calendarDays}
      </div>

      <div className="mt-6 flex items-center gap-3 text-xs text-gray-400 border-t border-gray-100 pt-4">
        <div className="flex items-center gap-1">
          <div className="w-2 h-13 rounded-full border border-primary" />
          <span>Hoy</span>
        </div>
        <div className="flex items-center gap-1">
          <div className="w-2 h-13 rounded-full bg-primary" />
          <span>Seleccionado</span>
        </div>
      </div>
    </div>
  );
};

// apps/frontend/src/lib/components/services/Calendar.svelte
<script lang="ts">
  import { ChevronLeft, ChevronRight, Calendar as CalendarIcon } from 'lucide-svelte';
  import { cn } from '$lib/utils/cn';
  import Typography from './Typography.svelte';

  interface Props {
    selectedDate?: string; // YYYY-MM-DD
    onDateSelect: (date: string) => void;
    minDate?: string;
    maxDate?: string;
  }

  let { selectedDate, onDateSelect, minDate, maxDate } = $props<Props>();

  let currentMonth = $state(new Date());

  const daysInMonth = (date: Date) => {
    return new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate();
  };

  const startDayOfMonth = (date: Date) => {
    const day = new Date(date.getFullYear(), date.getMonth(), 1).getDay();
    // Ajustar para que la semana empiece en Lunes (0=Dom, 1=Lun...)
    return day === 0 ? 6 : day - 1;
  };

  const isToday = (day: number) => {
    const today = new Date();
    return (
      day === today.getDate() &&
      currentMonth.getMonth() === today.getMonth() &&
      currentMonth.getFullYear() === today.getFullYear()
    );
  };

  const isSelected = (day: number) => {
    if (!selectedDate) return false;
    // Usar el mediodía para evitar problemas de zona horaria al formatear
    const date = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), day, 12, 0, 0);
    const dateStr = date.toISOString().split('T')[0];
    return dateStr === selectedDate;
  };

  const isDisabled = (day: number) => {
    const date = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), day, 12, 0, 0);
    const dateStr = date.toISOString().split('T')[0];
    
    if (minDate && dateStr < minDate) return true;
    if (maxDate && dateStr > maxDate) return true;
    return false;
  };

  const months = [
    'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
    'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
  ];

  const daysOfWeek = ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'];

  const prevMonth = () => {
    currentMonth = new Date(currentMonth.getFullYear(), currentMonth.getMonth() - 1);
  };

  const nextMonth = () => {
    currentMonth = new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1);
  };

  const handleDateClick = (day: number) => {
    if (isDisabled(day)) return;
    const date = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), day, 12, 0, 0);
    onDateSelect(date.toISOString().split('T')[0]);
  };

  // Derivados reactivos
  let totalDays = $derived(daysInMonth(currentMonth));
  let startOffset = $derived(startDayOfMonth(currentMonth));
</script>

<div class="p-4 bg-white rounded-4xl shadow-xl border border-gray-100 max-w-sm mx-auto">
  <div class="flex items-center justify-between mb-6">
    <div class="flex items-center gap-3">
      <div class="h-10 w-px0 rounded-4xl bg-primary/10 flex items-center justify-center text-primary">
        <CalendarIcon size={20} strokeWidth={2.5} />
      </div>
      <div>
        <Typography variant="h4" class="text-gray-900 mb-0! font-bold">
          {months[currentMonth.getMonth()]}
        </Typography>
        <Typography variant="small" class="text-gray-400 font-medium">
          {currentMonth.getFullYear()}
        </Typography>
      </div>
    </div>
    <div class="flex gap-2">
      <button
        onclick={prevMonth}
        class="h-10 w-px0 flex items-center justify-center rounded-4xl hover:bg-gray-50 border border-gray-100 transition-all active:scale-90"
      >
        <ChevronLeft size={20} class="text-gray-600" />
      </button>
      <button
        onclick={nextMonth}
        class="h-10 w-px0 flex items-center justify-center rounded-4xl hover:bg-gray-50 border border-gray-100 transition-all active:scale-90"
      >
        <ChevronRight size={20} class="text-gray-600" />
      </button>
    </div>
  </div>

  <div class="grid grid-cols-7 gap-1 mb-2">
    {#each daysOfWeek as day}
      <div class="h-10 w-px0 flex items-center justify-center">
        <Typography variant="small" class="text-gray-400 font-bold uppercase tracking-wider text-[10px]">
          {day}
        </Typography>
      </div>
    {/each}
  </div>

  <div class="grid grid-cols-7 gap-1">
    {#each Array(startOffset) as _}
      <div class="h-10 w-px0"></div>
    {/each}

    {#each Array(totalDays) as _, i}
      {@const d = i + 1}
      {@const disabled = isDisabled(d)}
      {@const selected = isSelected(d)}
      {@const today = isToday(d)}

      <button
        onclick={() => handleDateClick(d)}
        disabled={disabled}
        class={cn(
          "h-10 w-px0 rounded-4xl flex items-center justify-center text-sm transition-all font-medium relative focus:outline-none",
          selected 
            ? "bg-primary text-white font-bold shadow-lg shadow-primary/30 scale-105 z-10" 
            : "hover:bg-primary/10 text-gray-700 active:scale-95",
          today && !selected && "border-2 border-primary/30 text-primary font-bold",
          disabled && "text-gray-200 pointer-events-none"
        )}
      >
        {d}
        {#if today && !selected}
          <span class="absolute bottom-1 w-px h-1 bg-primary rounded-full"></span>
        {/if}
      </button>
    {/each}
  </div>
</div>
