// apps/frontend/src/lib/components/ui/Badge.svelte
<script lang="ts">
  import { cn } from '$lib/utils/cn';
  import type { HTMLAttributes } from 'svelte/elements';

  let { 
    variant = 'default', 
    class: className = '', 
    children,
    ...rest 
  } = $props<HTMLAttributes<HTMLSpanElement> & {
    variant?: 'default' | 'secondary' | 'outline' | 'destructive';
    children?: any;
    class?: string;
  }>();

  const variants = {
    default: 'bg-primary/10 text-primary border-primary/20',
    secondary: 'bg-secondary/10 text-secondary border-secondary/20',
    outline: 'border-gray-200 text-gray-600 bg-transparent',
    destructive: 'bg-red-50 text-red-600 border-red-100',
  };
</script>

<span
  class={cn(
    'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border',
    variants[variant],
    className
  )}
  {...rest}
>
  {@render children?.()}
</span>

// FRONTEND CON REACT FALLIDO/src/components/ui/Badge.tsx
import React from 'react';

interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  variant?: 'default' | 'secondary' | 'outline' | 'destructive';
}

export const Badge: React.FC<BadgeProps> = ({ 
  children, 
  variant = 'default', 
  className = '', 
  ...props 
}) => {
  const variants = {
    default: 'bg-primary/10 text-primary border-primary/20',
    secondary: 'bg-secondary/10 text-secondary border-secondary/20',
    outline: 'border-gray-200 text-gray-600 bg-transparent',
    destructive: 'bg-red-50 text-red-600 border-red-100',
  };

  return (
    <span
      className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${variants[variant]} ${className}`}
      {...props}
    >
      {children}
    </span>
  );
};
