// apps/frontend/src/lib/components/SearchBar.svelte
<script lang="ts">
  import { Search } from 'lucide-svelte';
  import { cn } from '$lib/utils/cn';
  import Input from './Input.svelte';

  interface Props {
    value: string;
    placeholder?: string;
    class?: string;
  }

  let { value = $bindable(), placeholder = "Buscar...", class: className = "" }: Props = $props();
</script>

<div class={cn("relative flex items-center group", className)}>
  <Search 
    class="absolute left-4 w-5 h-5 text-gray-400 group-focus-within:text-primary transition-colors pointer-events-none" 
  />
  <Input
    type="text"
    bind:value={value}
    {placeholder}
    class="pl-12 w-full h-[52px] shadow-sm hover:shadow-md focus:shadow-lg transition-all border-gray-100 !rounded-4xl"
  />
</div>

// FRONTEND CON REACT FALLIDO/src/components/ui/SearchBar.tsx
import React from 'react';
import { Search } from 'lucide-react';
import { Input } from './Input';

interface SearchBarProps {
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  className?: string;
}

export const SearchBar: React.FC<SearchBarProps> = ({
  value,
  onChange,
  placeholder = "Buscar...",
  className = ""
}) => {
  return (
    <div className={`relative flex items-center ${className}`}>
      <Search className="absolute left-3 w-4 h-4 text-gray-400" />
      <Input
        type="text"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        className="pl-10 w-full"
      />
    </div>
  );
};
