// FRONTEND CON REACT FALLIDO/src/components/ui/SearchBar.tsx
import React from 'react';
import { Search } from 'lucide-react';
import { Input } from './Input';

interface SearchBarProps {
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  className?: string;
}

export const SearchBar: React.FC<SearchBarProps> = ({
  value,
  onChange,
  placeholder = "Buscar...",
  className = ""
}) => {
  return (
    <div className={`relative flex items-center ${className}`}>
      <Search className="absolute left-3 w-4 h-4 text-gray-400" />
      <Input
        type="text"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        className="pl-10 w-full"
      />
    </div>
  );
};

// apps/frontend/src/lib/components/forms/SearchBar.svelte
<script lang="ts">
  import { cn } from '$lib/utils/cn';

  let { 
    value = $bindable(), 
    placeholder = "Buscar...", 
    class: className = "" 
  } = $props();
</script>

<div class={cn("relative flex items-center group w-full", className)}>
  <input
    type="text"
    bind:value={value}
    {placeholder}
    class="w-full h-13 bg-white border border-gray-100 rounded-4xl outline-none shadow-sm hover:shadow-md focus:shadow-lg focus:border-primary transition-all px-6 text-gray-700 placeholder:text-gray-400"
  />
</div>
