// src/components/ui/StarRating.tsx
import React, { useState } from 'react';
import { Star } from 'lucide-react';

interface StarRatingProps {
  rating: number;
  maxRating?: number;
  onRatingChange?: (rating: number) => void;
  readonly?: boolean;
  size?: number;
}

const StarRating: React.FC<StarRatingProps> = ({
  rating,
  maxRating = 5,
  onRatingChange,
  readonly = false,
  size = 24,
}) => {
  const [hoverRating, setHoverRating] = useState(0);

  return (
    <div className="flex items-center gap-1">
      {[...Array(maxRating)].map((_, index) => {
        const starValue = index + 1;
        const isActive = starValue <= (hoverRating || rating);
        
        return (
          <button
            key={index}
            type="button"
            disabled={readonly}
            className={`${readonly ? 'cursor-default' : 'cursor-pointer focus:outline-none focus:ring-2 focus:ring-primary/20 rounded-full'} transition-all duration-200 transform ${!readonly && starValue <= (hoverRating || rating) ? 'scale-110' : 'scale-100'}`}
            onClick={() => onRatingChange && onRatingChange(starValue)}
            onMouseEnter={() => !readonly && setHoverRating(starValue)}
            onMouseLeave={() => !readonly && setHoverRating(0)}
          >
            <Star
              size={size}
              className={`${
                isActive 
                  ? 'fill-amber-400 text-amber-400' 
                  : 'text-gray-300'
              } transition-colors duration-200`}
            />
          </button>
        );
      })}
    </div>
  );
};

export default StarRating;

// apps/frontend/src/lib/components/ui/StarRating.svelte
<script lang="ts">
  import { Star } from 'lucide-svelte';
  import { cn } from '$lib/utils/cn';
  import { calculateStarState } from '$lib/logic/StarRatingLogic';

  let { 
    rating, 
    maxRating = 5, 
    onRatingChange = () => {}, 
    readonly = false, 
    size = 24 
  } = $props<{
    rating: number;
    maxRating?: number;
    onRatingChange?: (rating: number) => void;
    readonly?: boolean;
    size?: number;
  }>();

  let hoverRating = $state(0);

  const handleClick = (value: number) => {
    if (!readonly && onRatingChange) {
      onRatingChange(value);
    }
  };
</script>

<div 
  role="group" 
  aria-label="Calificación con estrellas" 
  class="flex items-center gap-1.5" 
  onmouseleave={() => !readonly && (hoverRating = 0)}
>
  {#each Array(maxRating) as _, index}
    {@const { starValue, isActive } = calculateStarState(index, hoverRating, rating)}
    
    <button
      type="button"
      disabled={readonly}
      onclick={() => handleClick(starValue)}
      onmouseenter={() => !readonly && (hoverRating = starValue)}
      class={cn(
        "transition-all duration-300 transform outline-none",
        readonly ? 'cursor-default' : 'cursor-pointer hover:scale-125 active:scale-95 focus:ring-4 focus:ring-amber-100 rounded-full p-0.5',
        isActive && !readonly && "scale-110"
      )}
      aria-label="Calificar con {starValue} de {maxRating} estrellas"
    >
      <Star
        size={size}
        class={cn(
          "transition-all duration-300",
          isActive 
            ? 'fill-amber-400 text-amber-400 drop-shadow-[0_0_8px_rgba(251,191,36,0.5)]' 
            : 'text-gray-200'
        )}
      />
    </button>
  {/each}
</div>
