// apps/frontend/src/lib/components/ReviewList.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import StarRating from './StarRating.svelte';
  import Typography from './Typography.svelte';
  import Skeleton from './Skeleton.svelte';
  import { User, MessageSquare, Calendar } from 'lucide-svelte';

  interface Review {
    id: string;
    userName: string;
    comment: string;
    rating: number;
    createdAt: string;
  }

  interface Props {
    serviceId: string;
    key?: number;
  }

  let { serviceId, key = 0 }: Props = $props();
  let reviews = $state<Review[]>([]);
  let isLoading = $state(true);

  const fetchReviews = async () => {
    isLoading = true;
    try {
      const response = await fetch(`http://localhost:3000/api/reviews?serviceId=${serviceId}`);
      if (response.ok) {
        reviews = await response.json();
      }
    } catch (e) {
      console.error('Error fetching reviews:', e);
    } finally {
      isLoading = false;
    }
  };

  $effect(() => {
    // Re-fetch when serviceId or key changes
    if (serviceId || key) {
        fetchReviews();
    }
  });
</script>

<div class="space-y-8">
  {#if isLoading}
    {#each Array(3) as _}
        <div class="bg-white p-8 rounded-[32px] border border-gray-100 shadow-sm animate-pulse">
            <div class="flex items-center gap-4 mb-4">
                <Skeleton variant="circular" class="w-12 h-12" />
                <div class="space-y-2 flex-1">
                    <Skeleton variant="text" class="w-24 h-4" />
                    <Skeleton variant="text" class="w-16 h-3" />
                </div>
            </div>
            <Skeleton variant="text" class="w-full h-4" />
            <Skeleton variant="text" class="w-3/4 h-4 mt-2" />
        </div>
    {/each}
  {:else if reviews.length === 0}
    <div class="text-center py-20 bg-gray-50/50 rounded-[40px] border border-dashed border-gray-200">
      <MessageSquare size={48} class="text-gray-200 mx-auto mb-6" />
      <h3 class="text-xl font-bold text-gray-900 mb-2">Sin reseñas aún</h3>
      <p class="text-gray-400 font-medium max-w-xs mx-auto">Sé el primero en compartir tu experiencia sobre este servicio.</p>
    </div>
  {:else}
    <div class="grid grid-cols-1 gap-6">
      {#each reviews as review (review.id)}
        <div class="bg-white p-8 rounded-[32px] border border-gray-100 shadow-sm hover:shadow-xl hover:scale-[1.01] transition-all duration-500 group">
          <div class="flex items-center justify-between gap-4 mb-6">
            <div class="flex items-center gap-4">
              <div class="h-14 w-14 rounded-2xl bg-primary/5 flex items-center justify-center text-primary group-hover:bg-primary group-hover:text-white transition-all duration-500 border border-primary/10">
                <User size={28} />
              </div>
              <div>
                <h4 class="text-base font-black text-gray-900 leading-none mb-1">{review.userName || 'Usuario Anónimo'}</h4>
                <div class="flex items-center gap-2">
                  <Calendar size={12} class="text-primary/50" />
                  <span class="text-[10px] font-black uppercase tracking-widest text-gray-400">
                    {new Date(review.createdAt).toLocaleDateString()}
                  </span>
                </div>
              </div>
            </div>
            <div class="bg-amber-50 px-4 py-2 rounded-2xl border border-amber-100/50 flex items-center gap-2">
              <StarRating rating={review.rating} size={14} readonly />
              <span class="text-xs font-black text-amber-700">{review.rating}</span>
            </div>
          </div>
          
          <div class="relative pl-10">
            <div class="absolute left-0 top-0 text-5xl font-serif text-primary/10 leading-none">“</div>
            <p class="text-gray-600 font-medium leading-relaxed italic z-10 relative">
              {review.comment}
            </p>
          </div>
        </div>
      {/each}
    </div>
  {/if}
</div>

// FRONTEND CON REACT/src/features/catalog/components/ReviewList.tsx
import useSWR from 'swr';
import { fetcher } from '@/lib/fetcher';
import StarRating from '../../../components/ui/StarRating';
import { format } from 'date-fns';
import { es } from 'date-fns/locale';
import { User, MessageSquare } from 'lucide-react';

interface Review {
  id: string;
  rating: number;
  comment: string;
  createdAt: string;
  user: {
    firstName: string;
    lastName: string;
  };
}

interface ReviewListProps {
  serviceId: string;
}

const ReviewList: React.FC<ReviewListProps> = ({ serviceId }) => {
  const { data: reviews = [], error, isLoading } = useSWR<Review[]>(
    serviceId ? `/api/reviews?serviceId=${serviceId}` : null,
    fetcher
  );

  if (isLoading) {
    return (
      <div className="flex justify-center p-8">
        <div className="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-4 bg-red-50 text-red-700 rounded-4xl text-center">
        {error.message || 'Error al cargar las reseñas'}
      </div>
    );
  }

  if (reviews.length === 0) {
    return (
      <div className="text-center p-12 bg-gray-50 rounded-[2.5rem] border border-dashed border-gray-300">
        <MessageSquare className="mx-auto text-gray-300 mb-4" size={48} />
        <h4 className="text-xl font-bold text-gray-600">Aún no hay reseñas</h4>
        <p className="text-gray-500">Sé el primero en compartir tu experiencia.</p>
      </div>
    );
  }

  const averageRating = reviews.reduce((acc, curr) => acc + curr.rating, 0) / reviews.length;

  return (
    <div className="space-y-8">
      <div className="flex items-center gap-6 p-6 bg-white rounded-4xl border border-gray-100 shadow-sm">
        <div className="text-center">
          <div className="text-5xl font-black text-primary">{averageRating.toFixed(1)}</div>
          <div className="text-xs font-bold text-gray-400 uppercase tracking-widest mt-1">Puntuación</div>
        </div>
        <div className="h-12 w-px bg-gray-100"></div>
        <div className="flex-1">
          <StarRating rating={Math.round(averageRating)} readonly size={20} />
          <p className="text-sm text-gray-500 mt-1 font-medium">Basado en {reviews.length} {reviews.length === 1 ? 'reseña' : 'reseñas'}</p>
        </div>
      </div>

      <div className="grid gap-6">
        {reviews.map((review) => (
          <div key={review.id} className="bg-white p-6 rounded-4xl shadow-sm border border-gray-50 hover:border-primary/20 transition-colors">
            <div className="flex justify-between items-start mb-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-primary/10 rounded-full flex items-center justify-center text-primary">
                  <User size={20} />
                </div>
                <div>
                  <h5 className="font-bold text-gray-900 leading-tight">
                    {review.user.firstName} {review.user.lastName}
                  </h5>
                  <span className="text-xs text-gray-400 font-medium">
                    {format(new Date(review.createdAt), "d 'de' MMMM, yyyy", { locale: es })}
                  </span>
                </div>
              </div>
              <StarRating rating={review.rating} readonly size={16} />
            </div>
            {review.comment && (
              <p className="text-gray-600 leading-relaxed font-medium">
                "{review.comment}"
              </p>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};

export default ReviewList;
