// apps/frontend/src/lib/components/Card.svelte
<script lang="ts">
  import { cn } from '$lib/utils/cn';
  import type { HTMLAttributes } from 'svelte/elements';

  interface Props extends HTMLAttributes<HTMLDivElement> {
    hoverable?: boolean;
    children?: any;
  }

  let { 
    hoverable = false, 
    class: className = '', 
    children,
    ...rest 
  }: Props = $props();
</script>

<div
  class={cn(
    'bg-white rounded-2xl border border-gray-100 shadow-sm overflow-visible',
    hoverable && 'transition-all hover:shadow-md hover:border-primary/20',
    className
  )}
  {...rest}
>
  {@render children?.()}
</div>

// src/components/ui/Card.tsx
import React from 'react';
import { cn } from '@/lib/utils';

interface CardProps extends React.HTMLAttributes<HTMLDivElement> {
  hoverable?: boolean;
}

export const Card = ({ className, hoverable, children, ...props }: CardProps) => {
  return (
    <div
      className={cn(
        'bg-white rounded-2xl border border-gray-100 shadow-sm overflow-visible',
        hoverable && 'transition-all hover:shadow-md hover:border-primary/20',
        className
      )}
      {...props}
    >
      {children}
    </div>
  );
};

export const CardHeader = ({ className, children, ...props }: React.HTMLAttributes<HTMLDivElement>) => (
  <div className={cn('p-6 border-b border-gray-50', className)} {...props}>
    {children}
  </div>
);

export const CardContent = ({ className, children, ...props }: React.HTMLAttributes<HTMLDivElement>) => (
  <div className={cn('p-6', className)} {...props}>
    {children}
  </div>
);
