// apps/frontend/src/lib/components/ui/Dropdown.svelte
<script lang="ts">
  import { cn } from '$lib/utils/cn';

  let { 
    items = [], 
    trigger, 
    align = 'left', 
    class: className = '' 
  } = $props();

  let isOpen = $state(false);
  let dropdownRef = $state<HTMLElement | null>(null);

  const toggle = () => (isOpen = !isOpen);
  const close = () => (isOpen = false);

  const handleClickOutside = (event: MouseEvent) => {
    if (dropdownRef && !dropdownRef.contains(event.target as Node)) {
      close();
    }
  };

  $effect(() => {
    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside);
    } else {
      document.removeEventListener('mousedown', handleClickOutside);
    }
    return () => document.removeEventListener('mousedown', handleClickOutside);
  });
</script>

<div class={cn("relative inline-block", className)} bind:this={dropdownRef}>
  <div 
    onclick={toggle}
    onkeydown={(e) => e.key === 'Enter' && toggle()}
    role="button"
    tabindex="0"
    class="cursor-pointer outline-none"
  >
    {@render trigger()}
  </div>

  {#if isOpen}
    <div 
      class={cn(
        "absolute top-full mt-2 bg-white border border-gray-100 rounded-2xl shadow-2xl p-2 min-w-50 z-50",
        "animate-in fade-in zoom-in-95 duration-200 ease-out",
        align === 'right' ? 'right-0' : 'left-0'
      )}
    >
      <div class="flex flex-col gap-1 text-sm">
        {#each items as item}
          <button
            onclick={() => {
              item.onClick();
              close();
            }}
            class={cn(
              "flex items-center gap-3 px-3 py-2.5 rounded-xl transition-all w-full text-left font-medium",
              item.variant === 'danger' 
                ? 'text-red-500 hover:bg-red-50' 
                : 'text-gray-600 hover:bg-gray-50 active:scale-95'
            )}
          >
            {item.label}
          </button>
        {/each}
      </div>
    </div>
  {/if}
</div>

// src/components/ui/Dropdown.tsx
import React, { useState, useRef, useEffect, useId } from 'react';
import { ChevronDown } from 'lucide-react';

interface DropdownItem {
  label: string;
  onClick: () => void;
  icon?: React.ReactNode;
  variant?: 'default' | 'danger';
}

interface DropdownProps {
  trigger: React.ReactNode;
  items: DropdownItem[];
  align?: 'left' | 'right';
  className?: string;
}

export const Dropdown: React.FC<DropdownProps> = ({ 
  trigger, 
  items, 
  align = 'right',
  className = '' 
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };

    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside);
    }
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [isOpen]);

  return (
    <div className={`relative inline-block ${className}`} ref={dropdownRef}>
      <div 
        onClick={() => setIsOpen(!isOpen)}
        className="cursor-pointer"
      >
        {trigger}
      </div>

      {isOpen && (
        <div 
          className={`
            absolute top-full mt-2 bg-white border border-gray-200 rounded-lg shadow-xl p-1 min-w-40 z-9999
            animate-in fade-in zoom-in-95 duration-100
            ${align === 'right' ? 'right-0' : 'left-0'}
          `}
        >
          <div className="flex flex-col gap-1">
            {items.map((item, index) => (
              <button
                key={index}
                onClick={() => {
                  item.onClick();
                  setIsOpen(false);
                }}
                className={`
                  flex items-center gap-2 px-3 py-2 text-sm rounded-md transition-colors w-full text-left
                  ${item.variant === 'danger' 
                    ? 'text-red-600 hover:bg-red-50' 
                    : 'text-gray-700 hover:bg-gray-100'}
                `}
              >
                {item.icon && <span className="shrink-0">{item.icon}</span>}
                {item.label}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
