// apps/frontend/src/lib/components/ui/Input.svelte
<script lang="ts">
  import { cn } from '$lib/utils/cn';
  import type { HTMLInputAttributes } from 'svelte/elements';

  let { 
    id = "input-" + Math.floor(Math.random() * 1000000),
    label, 
    error, 
    value = $bindable(), 
    class: className = '',
    type = 'text',
    ...rest 
  } = $props<HTMLInputAttributes & {
    id?: string;
    label?: string;
    error?: string;
    value?: string | number;
    placeholder?: string;
    class?: string;
    type?: string;
  }>();
</script>

<div class="w-full space-y-1.5">
  {#if label}
    <label for={id} class="text-sm font-semibold text-gray-700 ml-1">
      {label}
    </label>
  {/if}
  <div class="relative group">
    <input
      {id}
      {type}
      class={cn(
        'w-full bg-white border border-gray-200 rounded-xl px-4 py-2.5 outline-none transition-all focus:border-primary focus:ring-4 focus:ring-primary/10 placeholder:text-gray-400 text-gray-700',
        error && 'border-red-500 focus:border-red-500 focus:ring-red-100',
        className
      )}
      bind:value
      {...rest}
    />
  </div>
  {#if error}
    <p class="text-xs text-red-500 ml-1 mt-1 flex items-center gap-1">
      <span>{error}</span>
    </p>
  {/if}
</div>

// src/components/ui/Input.tsx
import React from 'react';
import { cn } from '@/lib/utils';

interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  error?: string;
  icon?: React.ReactNode;
}

export const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, label, error, icon, ...props }, ref) => {
    return (
      <div className="w-full space-y-1.5">
        {label && (
          <label className="text-sm font-semibold text-gray-700 ml-1">
            {label}
          </label>
        )}
        <div className="relative group">
          {icon && (
            <div className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 group-focus-within:text-primary transition-colors">
              {icon}
            </div>
          )}
          <input
            ref={ref}
            className={cn(
              'w-full bg-white border border-gray-200 rounded-xl px-4 py-2.5 outline-none transition-all focus:border-primary focus:ring-4 focus:ring-primary/10 placeholder:text-gray-400 text-gray-700',
              icon && 'pl-10',
              error && 'border-red-500 focus:border-red-500 focus:ring-red-100',
              className
            )}
            {...props}
          />
        </div>
        {error && (
          <p className="text-xs text-red-500 ml-1 mt-1 flex items-center gap-1">
            <span>{error}</span>
          </p>
        )}
      </div>
    );
  }
);

Input.displayName = 'Input';
