// apps/frontend/src/lib/components/ui/Modal.svelte
<script lang="ts">
  import { X } from 'lucide-svelte';
  import { cn } from '$lib/utils/cn';
  import Typography from './Typography.svelte';
  import type { Snippet } from 'svelte';

  let { 
    isOpen, 
    onClose, 
    title, 
    children, 
    footer, 
    size = 'md' 
  } = $props<{
    isOpen: boolean;
    onClose: () => void;
    title: string;
    children: Snippet;
    footer?: Snippet;
    size?: 'sm' | 'md' | 'lg' | 'xl' | 'full';
  }>();

  const sizeClasses = {
    sm: 'max-w-md',
    md: 'max-w-lg',
    lg: 'max-w-2xl',
    xl: 'max-w-4xl',
    full: 'max-w-[95%] h-[95%]',
  };

  const handleEscape = (e: KeyboardEvent) => {
    if (e.key === 'Escape' && isOpen) onClose();
  };

  $effect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
      window.addEventListener('keydown', handleEscape);
    } else {
      document.body.style.overflow = 'unset';
      window.removeEventListener('keydown', handleEscape);
    }
  });
</script>

{#if isOpen}
  <div class="fixed inset-0 z-100 flex items-center justify-center p-4 sm:p-6 sm:pb-24">
    <!-- Overlay -->
    <div 
      class="absolute inset-0 bg-black/40 backdrop-blur-md transition-opacity animate-in fade-in duration-300"
      onclick={onClose}
      aria-hidden="true"
    ></div>
    
    <!-- Modal Content -->
    <div 
      class={cn(
        "relative w-full bg-white shadow-2xl rounded-4xl overflow-hidden transition-all transform animate-in fade-in zoom-in-95 duration-200",
        sizeClasses[size]
      )}
    >
      <div class="flex items-center justify-between p-6 sm:px-8 border-b border-gray-100">
        <Typography variant="h4" class="mb-0! font-bold text-gray-900">
          {title}
        </Typography>
        <button 
          onclick={onClose}
          class="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-4xl transition-all active:scale-90"
        >
          <X size={24} />
        </button>
      </div>

      <div class="p-6 sm:p-8 overflow-y-auto max-h-[calc(100vh-16rem)]">
        {@render children()}
      </div>

      {#if footer}
        <div class="p-6 sm:px-8 border-t border-gray-100 bg-gray-50/50 flex justify-end gap-3">
          {@render footer()}
        </div>
      {/if}
    </div>
  </div>
{/if}

// src/components/ui/Modal.tsx
import React, { useEffect, useRef } from 'react';
import { X } from 'lucide-react';
import { Button } from '@components/ui/Button';
import { Typography } from '@components/ui/Typography';
import { cn } from '@/lib/utils';

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  children: React.ReactNode;
  footer?: React.ReactNode;
  size?: 'sm' | 'md' | 'lg' | 'xl' | 'full';
}

export const Modal: React.FC<ModalProps> = ({
  isOpen,
  onClose,
  title,
  children,
  footer,
  size = 'md',
}) => {
  const modalRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };

    if (isOpen) {
      document.body.style.overflow = 'hidden';
      window.addEventListener('keydown', handleEscape);
    }

    return () => {
      document.body.style.overflow = 'unset';
      window.removeEventListener('keydown', handleEscape);
    };
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const sizeClasses = {
    sm: 'max-w-md',
    md: 'max-w-lg',
    lg: 'max-w-2xl',
    xl: 'max-w-4xl',
    full: 'max-w-[95%] h-[95%]',
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6">
      <div 
        className="absolute inset-0 bg-black/40 backdrop-blur-sm transition-opacity"
        onClick={onClose}
      />
      
      <div 
        ref={modalRef}
        className={cn(
          "relative w-full bg-white shadow-2xl rounded-3xl overflow-hidden transition-all transform animate-in fade-in zoom-in duration-200",
          sizeClasses[size]
        )}
      >
        <div className="flex items-center justify-between p-6 border-b border-gray-100">
          <Typography variant="h4" className="m-0 font-bold text-gray-800">
            {title}
          </Typography>
          <button 
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-full transition-colors"
          >
            <X size={20} />
          </button>
        </div>

        <div className="p-6 overflow-y-auto max-h-[calc(100vh-12rem)]">
          {children}
        </div>

        {footer && (
          <div className="p-6 border-t border-gray-100 bg-gray-50/50 flex justify-end gap-3">
            {footer}
          </div>
        )}
      </div>
    </div>
  );
};
